export type Product = {
  id: string;
  name: string;
  line: string;
  lines: string[];
  size: string;
  use: string;
  colors: string;
  url: string | null;
  pdf?: string;
};
export const products: Product[] = [
  {
    id: 'acetica',
    name: 'Silicona acética',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '280 cc',
    use: 'Para sellar y pegar vidrio, chapa, madera, cerámicas y azulejos.',
    colors: 'Transparente, blanco y negro.',
    url: 'sellador-acetico-pegalo',
    pdf: 'Pegalo-Acetic-Silicone-Sealant-TDS.pdf',
  },
  {
    id: 'neutra',
    name: 'Silicona neutra',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '280 cc',
    use: 'Sellador adhesivo de uso profesional para vidrio, espejos, policarbonato y mampostería.',
    colors: 'Transparente, blanco y negro.',
    url: 'silicona-neutra',
  },
  {
    id: 'contacto',
    name: 'Adhesivo de contacto',
    line: 'Pegalo',
    lines: ['Pegalo'],
    size: '500 cc',
    use: 'Adhesivo de uso industrial para madera, textiles y revestimientos.',
    colors: 'Consultar disponibilidad.',
    url: null,
  },
  {
    id: 'espuma',
    name: 'Espuma de poliuretano',
    line: 'Artesanato',
    lines: ['Artesanato', 'Instalador'],
    size: '500 ml',
    use: 'Para rellenar, obturar, sellar y fijar en construcción e industria.',
    colors: 'Consultar disponibilidad.',
    url: 'espuma-de-poliuretano',
  },
  {
    id: 'artesanato',
    name: 'Silicona acética Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato', 'Instalador'],
    size: '280 ml',
    use: 'Sellador para construcción, reparaciones e instalaciones.',
    colors: 'Transparente.',
    url: 'silicona-acetica-artesanato',
  },
  {
    id: 'acrilico',
    name: 'Sellador acrílico',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '280 g',
    use: 'Para juntas, marcos de puertas y ventanas y grietas en paredes y techos.',
    colors: 'Blanco.',
    url: 'sellador-acrilico',
  },
  {
    id: 'temperatura',
    name: 'Silicona alta temperatura',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '280 cc · 32 cc',
    use: 'Sellador para juntas en aplicaciones de temperatura elevada. Consultá la ficha técnica para tu uso específico.',
    colors: 'Consultar disponibilidad.',
    url: 'sellador-alta-temperatura',
  },
  {
    id: 'construccion',
    name: 'Poliuretano construcción e industria',
    line: 'Artesanato',
    lines: ['Artesanato', 'Instalador'],
    size: '310 ml',
    use: 'Sellador de poliuretano para juntas en construcción e industria.',
    colors: 'Gris y blanco.',
    url: 'poliuretano-construccion-industria',
  },
  {
    id: 'automotor',
    name: 'Poliuretano 628 automotor',
    line: 'Artesanato',
    lines: ['Artesanato', 'Instalador'],
    size: '310 ml',
    use: 'Poliuretano para aplicaciones de sellado y adhesión en la industria automotriz.',
    colors: 'Negro.',
    url: 'poliuretano-628-automotor',
  },
  {
    id: 'zingueria',
    name: 'Sellador de zinguería y canaletas',
    line: 'Artesanato',
    lines: ['Artesanato', 'Instalador'],
    size: '280 cc',
    use: 'Para el pegado y sellado de chapas, canaletas y trabajos de zinguería.',
    colors: 'Aluminio.',
    url: 'sellador-para-zingueria',
  },
  {
    id: 'cola',
    name: 'Cola vinílica',
    line: 'Pegalo',
    lines: ['Pegalo'],
    size: '125 ml',
    use: 'Adhesivo de base acuosa para madera, cartón y trabajos de carpintería.',
    colors: 'Consultar disponibilidad.',
    url: 'cola-vinilica-pegalo',
  },
  {
    id: 'epoxi',
    name: 'Crema para bachas epoxi',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: 'Blanca · Acero',
    use: 'Adhesivo epoxi de dos componentes para fijar, pegar y reparar.',
    colors: 'Blanca y acero.',
    url: 'crema-para-bachas-blanca-y-acero',
  },
  {
    id: 'roscas',
    name: 'Sellador de roscas',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '25 cc',
    use: 'Para el sellado de conexiones sanitarias de agua caliente y fría.',
    colors: 'Verde.',
    url: 'sellador-de-roscas',
  },
  {
    id: 'teflon',
    name: 'Cinta teflón',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '12 mm × 0,075 mm × 10 m',
    use: 'Para el sellado de conexiones roscadas de plástico y metal.',
    colors: 'Blanco.',
    url: 'cinta-teflon',
  },
  {
    id: 'lubricante',
    name: 'Lubricante multiusos',
    line: 'Artesanato',
    lines: ['Artesanato'],
    size: '450 cc',
    use: 'Afloja piezas oxidadas, desplaza la humedad y lubrica mecanismos.',
    colors: 'Presentación en aerosol.',
    url: null,
  },
  {
    id: 'flexitapa',
    name: 'Lubricante con flexitapa',
    line: 'Artesanato',
    lines: ['Artesanato'],
    size: '450 cc',
    use: 'Lubricante multiusos con aplicador para alcanzar zonas de difícil acceso.',
    colors: 'Presentación con flexitapa.',
    url: null,
  },
  {
    id: 'liquida',
    name: 'Silicona líquida',
    line: 'Artesanato',
    lines: ['Artesanato'],
    size: '30 g',
    use: 'Para pegar materiales de manualidades como papel, goma eva, tela, corcho y madera.',
    colors: 'Consultar disponibilidad.',
    url: 'silicona-liquida',
  },
  {
    id: 'barras',
    name: 'Barras adhesivas Hot Melt',
    line: 'Artesanato',
    lines: ['Artesanato'],
    size: 'Barras finas y gruesas',
    use: 'Adhesivo en barras para aplicar con pistola eléctrica en manualidades y proyectos.',
    colors: 'Consultar presentaciones.',
    url: 'barras-adhesivas-hot-melt',
  },
  {
    id: 'hotmelt',
    name: 'Pistola Hot Melt',
    line: 'Artesanato',
    lines: ['Artesanato'],
    size: 'Aplicador eléctrico',
    use: 'Pistola eléctrica para aplicar barras adhesivas Hot Melt.',
    colors: 'Consultar modelos.',
    url: 'pistola-aplicadora-de-hot-melt',
  },
  {
    id: 'pistola',
    name: 'Pistola aplicadora',
    line: 'Instalador',
    lines: ['Instalador'],
    size: 'Liviana · Reforzada',
    use: 'Aplicador manual para selladores y adhesivos presentados en cartuchos.',
    colors: 'Dos modelos.',
    url: 'pistola-aplicadora',
  },
  {
    id: 'ciano-10',
    name: 'Cianoacrilato 10 g',
    line: 'Pegalo',
    lines: ['Pegalo'],
    size: '10 g',
    use: 'Adhesivo instantáneo de uso profesional para múltiples materiales.',
    colors: 'Consultar disponibilidad.',
    url: 'cianocrilato-pegalo',
  },
  {
    id: 'ciano-20',
    name: 'Cianoacrilato 20 g',
    line: 'Pegalo',
    lines: ['Pegalo'],
    size: '20 g',
    use: 'Adhesivo instantáneo de uso profesional para múltiples materiales.',
    colors: 'Consultar disponibilidad.',
    url: 'cianocrilato-pegalo',
  },
  {
    id: 'ciano-100',
    name: 'Cianoacrilato 100 g',
    line: 'Pegalo',
    lines: ['Pegalo'],
    size: '100 g',
    use: 'Adhesivo instantáneo de uso profesional para múltiples materiales.',
    colors: 'Consultar disponibilidad.',
    url: 'cianocrilato-pegalo',
  },
];

export const productFamilies = [
  {
    name: 'Adhesivos',
    ids: [
      'ciano-10',
      'ciano-20',
      'ciano-100',
      'contacto',
      'cola',
      'epoxi',
      'liquida',
    ],
  },
  {
    name: 'Siliconas y selladores',
    ids: [
      'acetica',
      'neutra',
      'artesanato',
      'acrilico',
      'temperatura',
      'zingueria',
      'roscas',
    ],
  },
  { name: 'Poliuretanos', ids: ['espuma', 'construccion', 'automotor'] },
  { name: 'Hot melt y aplicadores', ids: ['barras', 'hotmelt', 'pistola'] },
  { name: 'Complementos', ids: ['teflon', 'lubricante', 'flexitapa'] },
];
