export type Product = {
  id: string;
  name: string;
  line: string;
  lines: string[];
  size: string;
  use: string;
  colors: string;
  url: string | null;
  pdf?: string;
};
export const products: Product[] = [
  {
    id: 'acetica',
    pdf: '/fichas/ficha-silicona-acetica-pegalo.pdf',
    name: 'Silicona Acetica Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '280 cc (transparente, blanca y negra); 32 cc y 85 cc (solo transparente).',
    use: 'Sellador de silicona acetica anti-hongos ideal para sellar y pegar diferentes materiales, tales como vidrios, chapa, madera, cerámicas, azulejos, etc.',
    colors: 'Transparente, blanca y negra, según presentación.',
    url: 'sellador-acetico-pegalo',
  },
  {
    id: 'neutra',
    pdf: '/fichas/ficha-silicona-neutra-pegalo.pdf',
    name: 'Silicona Neutra Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '280 cc',
    use: 'Sellador adhesivo de silicona neutra. Ideal para ser utilizado en el sellado de vidrios, espejos, policarbonatos, mampostería, plásticos, chapas, fibras de vidrio, etc.',
    colors: 'Transparente, blanca y negra.',
    url: 'silicona-neutra',
  },
  {
    id: 'artesanato',
    pdf: '/fichas/ficha-silicona-acetica-artesanato.pdf',
    name: 'Silicona Acetica Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato', 'Instalador'],
    size: '280 cc',
    use: 'Sellador de silicona acetico, ideal para ser utilizado en la industria de la construcción, reparaciones, automotrices, ingeniería sanitaria y náutica.',
    colors: 'Transparente.',
    url: 'silicona-acetica-artesanato',
  },
  {
    id: 'temperatura',
    pdf: '/fichas/ficha-alta-temperatura-pegalo.pdf',
    name: 'Silicona Alta Temperatura Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '32 cc, 85 cc y 280 cc',
    use: 'Sellador ideal para realizar juntas en lugares de temperaturas elevadas, como motores, radiadores, termotanques, etc.',
    colors: 'Rojo.',
    url: 'sellador-alta-temperatura',
  },
  {
    id: 'construccion',
    pdf: '/fichas/ficha-PU-construccion-artesanato.pdf',
    name: 'Poliuretano Construccion Industria Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato', 'Instalador'],
    size: '310 cc (gris y blanco); 600 cc (solo gris).',
    use: 'Sellador de alta resistencia para juntas de dilatación en la industria de la construcción, mecánica y automotriz. Aplicable en metales, plásticos, madera, goma, vidrio, etc.',
    colors: 'Gris y blanco, según presentación.',
    url: 'poliuretano-construccion-industria',
  },
  {
    id: 'automotor',
    pdf: '/fichas/ficha-pu-628-automotor-artesanato.pdf',
    name: 'Poliuretano 628 Automotor Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato', 'Instalador'],
    size: '310 cc y 600 cc',
    use: 'Utilizado en aplicaciones en la industria mecánica y automotriz. Para el sellado y adhesión de parabrisas. Aplicable en metales, plásticos, madera, goma, vidrio, etc.',
    colors: 'Negro.',
    url: 'poliuretano-628-automotor',
  },
  {
    id: 'zingueria',
    pdf: '/fichas/ficha-sellador-zingueria-artesanato.pdf',
    name: 'Sellador de Zingueria y Canaletas Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato', 'Instalador'],
    size: '280 cc',
    use: 'Formulado para el pegado y sellado de todo tipo de zingueria, chapas, canaletas.',
    colors: 'Aluminio.',
    url: 'sellador-para-zingueria',
  },
  {
    id: 'acrilico',
    pdf: '/fichas/ficha-sellador-acrilico-pegalo.pdf',
    name: 'Sellador Acrilico Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '280 cc',
    use: 'Es un producto ideal para sellar juntas en el ambito de la construccion, como marcos de puertas y ventanas a griteas en paredes y techos. Fraguado total despues de las 24hs de aplicado.',
    colors: 'Blanco.',
    url: 'sellador-acrilico',
  },
  {
    id: 'contacto',
    pdf: '/fichas/ficha-adhesivo-de-contacto-pegalo.pdf',
    name: 'Adhesivo de Contacto Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo'],
    size: '125 cc, 250 cc, 500 cc, 1 L, 4 L, 10 L y 18 L',
    use: 'Adhesivo de contacto a base de cauchos cloroprenos. Uso en maderas, laminados, decorativos, calzados, cueros y mas.',
    colors: '',
    url: null,
  },
  {
    id: 'cola',
    pdf: '/fichas/ficha-cola-vinilica-pegalo.pdf',
    name: 'Cola Vinilica Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo'],
    size: '125 cc, 250 cc, 500 cc, 1 L, 4 L y 20 L',
    use: 'Cola vinílica de carpintería, con base acuosa para pegado de maderas, cartón, masa de porcelana y otros.',
    colors: '',
    url: 'cola-vinilica-pegalo',
  },
  {
    id: 'epoxi',
    pdf: '/fichas/ficha-crema-epoxy-pegalo.pdf',
    name: 'Crema para Bachas Epoxi Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '150 g (blanca); 200 g (acero).',
    use: 'Crema epoxi de secado lento y gran poder de adhesión especialmente indicada para la unión de bachas de mesadas.',
    colors: 'Blanca y acero, según presentación.',
    url: 'crema-para-bachas-blanca-y-acero',
  },
  {
    id: 'roscas',
    pdf: '/fichas/ficha-sella-roscas-pegalo.pdf',
    name: 'Sellador de Roscas Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '25 cc',
    use: 'Indicado para el sellado de conexiones de agua fría y caliente, su gran elasticidad permite absorber la dilatación y contracción de los materiales.',
    colors: 'Verde.',
    url: 'sellador-de-roscas',
  },
  {
    id: 'teflon',
    pdf: '/fichas/ficha-cinta-de-teflon-pegalo.pdf',
    name: 'Cinta de Teflon Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo', 'Instalador'],
    size: '12, 19 y 25',
    use: 'Muy buena resistencia a las rasgaduras, es químicamente inerte y sella la mayoría de tuberías y pernos roscados metálicos y de plástico.',
    colors: '',
    url: 'cinta-teflon',
  },
  {
    id: 'barras',
    pdf: '/fichas/ficha-barras-hotmelt-artesanato.pdf',
    name: 'Barras Adhesivas Hotmelt Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato'],
    size: 'Barras finas y gruesas, 1 kg',
    use: 'Adhesivo siliconado en barra, ideal para manualidades, hobbies, etc. Se aplica con pistola eléctrica.',
    colors: 'Transparente.',
    url: 'barras-adhesivas-hot-melt',
  },
  {
    id: 'hotmelt',
    pdf: '/fichas/ficha-pistola-pegamento-hotmelt-artesanato.pdf',
    name: 'Pistola Hotmelt Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato'],
    size: 'Pistola fina (10 W) y gruesa (60 W)',
    use: 'Es una pistola eléctrica para la aplicación de las barras adhesivas de HotMelt. Es ideal para manualidades.',
    colors: '',
    url: 'pistola-aplicadora-de-hot-melt',
  },
  {
    id: 'liquida',
    pdf: '/fichas/ficha-silicona-liquida-artesanato.pdf',
    name: 'Silicona Liquida Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato'],
    size: '30 g y 100 g',
    use: 'Especialmente formulado para pegar los mas diversos materiales sin el uso de pistola aplicadora. Adhiere papel, goma eva, tela, corcho, madera, etc.',
    colors: '',
    url: 'silicona-liquida',
  },
  {
    id: 'ciano-10',
    pdf: '/fichas/ficha-cianocrilato-pegalo.pdf',
    name: 'Cianoacrilato Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo'],
    size: '10 g',
    use: 'Adhesivo instantáneo ideal para pegar en segundos una gama muy amplia de superficies y materiales, tales como: goma, vidrio, cerámica, metal, plásticos, madera, cuero, etc.',
    colors: '',
    url: 'cianocrilato-pegalo',
  },
  {
    id: 'ciano-20',
    pdf: '/fichas/ficha-cianocrilato-pegalo.pdf',
    name: 'Cianoacrilato Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo'],
    size: '20 g',
    use: 'Adhesivo instantáneo ideal para pegar en segundos una gama muy amplia de superficies y materiales, tales como: goma, vidrio, cerámica, metal, plásticos, madera, cuero, etc.',
    colors: '',
    url: 'cianocrilato-pegalo',
  },
  {
    id: 'ciano-100',
    pdf: '/fichas/ficha-cianocrilato-pegalo.pdf',
    name: 'Cianoacrilato Pegalo',
    line: 'Pegalo',
    lines: ['Pegalo'],
    size: '100 g',
    use: 'Adhesivo instantáneo ideal para pegar en segundos una gama muy amplia de superficies y materiales, tales como: goma, vidrio, cerámica, metal, plásticos, madera, cuero, etc.',
    colors: '',
    url: 'cianocrilato-pegalo',
  },
  {
    id: 'espuma',
    pdf: '/fichas/ficha-espuma-PU-artesanato.pdf',
    name: 'Espuma de Poliuretano expandido Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato', 'Instalador'],
    size: '300 cc y 500 cc',
    use: 'Para rellenar, obturar, sellar, fijar. Aislante del frio y del calor. Expande 3 a 4 veces su volumen inicial. Uso profesional, en construcción e industrias.',
    colors: '',
    url: 'espuma-de-poliuretano',
  },
  {
    id: 'pistola',
    pdf: '/fichas/ficha-pistola-aplicadora-pegalo.pdf',
    name: 'Pistola Aplicadora Pegalo',
    line: 'Instalador',
    lines: ['Instalador'],
    size: 'Chapa cerrada (azul); esqueleto (naranja).',
    use: 'Para uso manual para la aplicación de los productos presentados en cartuchos de 280cc, 300cc y 310cc.',
    colors: 'Azul y naranja, según modelo.',
    url: 'pistola-aplicadora',
  },
  {
    id: 'lubricante',
    pdf: '/fichas/ficha-lubricante-aerosol-artesanato.pdf',
    name: 'Lubricante Multiusos Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato'],
    size: '250 cc y 450 cc',
    use: 'Aerosol Multiusos: elimina ruidos, desplaza la humedad, limpia y protege, afloja las piezas oxidadas, libera mecanismos trabados.',
    colors: '',
    url: null,
  },
  {
    id: 'flexitapa',
    pdf: '/fichas/ficha-lubricante-aerosol-artesanato.pdf',
    name: 'Lubricante con Flexitapa Artesanato',
    line: 'Artesanato',
    lines: ['Artesanato'],
    size: '250 cc y 450 cc',
    use: 'Lubricante Multiusos con Flexitapa, una solución completa para eliminar ruidos, desplazar la humedad, limpiar y proteger, aflojar piezas oxidadas y destrabar mecanismos con máxima precisión.',
    colors: '',
    url: null,
  },
];

export const productFamilies = [
  {
    name: 'Adhesivos',
    ids: [
      'ciano-10',
      'ciano-20',
      'ciano-100',
      'contacto',
      'cola',
      'epoxi',
      'liquida',
    ],
  },
  {
    name: 'Siliconas y selladores',
    ids: [
      'acetica',
      'neutra',
      'artesanato',
      'acrilico',
      'temperatura',
      'zingueria',
      'roscas',
    ],
  },
  { name: 'Poliuretanos', ids: ['espuma', 'construccion', 'automotor'] },
  { name: 'Hot melt y aplicadores', ids: ['barras', 'hotmelt', 'pistola'] },
  { name: 'Complementos', ids: ['teflon', 'lubricante', 'flexitapa'] },
];
